services:
  web:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm start